media: i2c: Fix a build error in ar0234.c
Fixing build issues:

drivers/media/i2c/ar0234.c: In function 'ar0234_set_ctrl':
drivers/media/i2c/ar0234.c:507:3: error: a label can only be part of a statement and a declaration is not a statement
507 |   u64 reg;
	|   ^~~

Fixes: f1d1d3f60e98 ("media: i2c: Add ar0234 camera sensor driver")

Signed-off-by: Qiao, Wei <wei.qiao@intel.com>