arm64: fpsimd: dovetail: Fix a build error in arch/arm64/kernel/fpsimd.c
arch/arm64/kernel/fpsimd.c:261:1: error: expected identifier or '(' before '}' token
261 | }
    | ^

Fixes: ed903e95019c ("arm64: fpsimd: dovetail: enable alternate scheduling")

Signed-off-by: Qiao, Wei <wei.qiao@intel.com>