ASoC: Intel: FPGA: Fix build error for mips
Below build regression observed for mips with allmodconfig:

sound/soc/intel/fpga/hda_intel_cnl_fpga.c:277:1: error: type defaults
to 'int' in declaration of 'module_pci_driver' [-Werror=implicit-int]

To fix this, x86 dependency added to SND_SOC_INTEL_CNL_FPGA.

Change-Id: Ia975415cafad536832d3383ed3e8c4314bf0d301
Signed-off-by: Anamika Lal <anamikax.lal@intel.com>
Reviewed-on: https://git-gar-1.devtools.intel.com/gerrit/17517
Reviewed-by: Diwakar, Praveen <praveen.diwakar@intel.com>
Reviewed-by: Singh, Guneshwor O <guneshwor.o.singh@intel.com>
Reviewed-by: Koul, Vinod <vinod.koul@intel.com>
Tested-by: Sm, Bhadur A <bhadur.a.sm@intel.com>