ANDROID: Fix kernelci build-break
Fix build break when !CONFIG_PCIEASPM:

drivers/pci/pci.h:613:61: error: expected identifier or '('
  613 | static inline void pci_save_ltr_state(struct pci_dev *dev); { }
      |                                                             ^
drivers/pci/pci.h:614:64: error: expected identifier or '('
  614 | static inline void pci_restore_ltr_state(struct pci_dev *dev); { }

  ...

Fixes: a9ce883fd2ce ("BACKPORT: PCI/ASPM: Save L1 PM Substates Capability for suspend/resume")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: Idf40e8bff6b3df3202afaa3989f45428025e6243