ANDROID: net: PPPoPNS and PPPoLAC build fixes for 4.14
Fix the build error because the return type of skb_push is void * on 4.14.

../../../../../../kernel/4.14/drivers/net/ppp/pppolac.c: In function 'pppolac_recv_core':
../../../../../../kernel/4.14/drivers/net/ppp/pppolac.c:133:19: warning: dereferencing 'void *' pointer
   skb_push(skb, 1)[0] = 0;
                   ^
../../../../../../kernel/4.14/drivers/net/ppp/pppolac.c:133:3: error: invalid use of void expression
   skb_push(skb, 1)[0] = 0;

Signed-off-by: Pan, Kris <kris.pan@intel.com>