mfd: change Broxton PMC driver to built-in only
Since iTCO_WDT changed to built-in only, we need to force PMC driver as
well.

ld: drivers/watchdog/iTCO_wdt.o: in function `update_no_reboot_bit_pmc':
iTCO_wdt.c:(.text+0xc27): undefined reference to `intel_pmc_gcr_update'
make: *** [Makefile:1219: vmlinux] Error 1

Signed-off-by: Pan, Kris <kris.pan@intel.com>