Revert "FROMGIT: kallsyms: unexport kallsyms_lookup_name() and kallsyms_on_each_symbol()"
This reverts commit 8e37367a324263c8c1b31ab14030d6be27b0cc7e.

ERROR: "kallsyms_lookup_name" [drivers/platform/x86/sepdk/sep/sep5.ko] undefined!
scripts/Makefile.modpost:108: recipe for target '__modpost' failed
make[1]: *** [__modpost] Error 1
Makefile:1344: recipe for target 'modules' failed
make: *** [modules] Error 2

Signed-off-by: Pan, Kris <kris.pan@intel.com>